<?php

/**
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

namespace yii\grid;

use Closure;
use Yii;
use yii\base\InvalidConfigException;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\jquery\grid\CheckboxColumnJqueryClientScript;
use yii\web\client\ClientScriptInterface;

use function call_user_func;
use function is_array;

/**
 * CheckboxColumn displays a column of checkboxes in a grid view.
 *
 * To add a CheckboxColumn to the [[GridView]], add it to the [[GridView::columns|columns]] configuration as follows:
 *
 * ```
 * 'columns' => [
 *     // ...
 *     [
 *         'class' => 'yii\grid\CheckboxColumn',
 *         // you may configure additional properties here
 *     ],
 * ]
 * ```
 *
 * Users may click on the checkboxes to select rows of the grid. The selected rows may be
 * obtained by calling the following JavaScript code:
 *
 * ```
 * var keys = $('#grid').yiiGridView('getSelectedRows');
 * // keys is an array consisting of the keys associated with the selected rows
 * ```
 *
 * For more details and usage information on CheckboxColumn, see the [guide article on data widgets](guide:output-data-widgets).
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class CheckboxColumn extends Column
{
    /**
     * @var string the name of the input checkbox input fields. This will be appended with `[]` to ensure it is an array.
     */
    public $name = 'selection';
    /**
     * @var string|null the value that should be submitted when none of the checkboxes is selected.
     * By default, this is an empty string. Set this property to `null` to disable hidden input generation.
     */
    public $unselect = '';
    /**
     * @var array the HTML attributes for the hidden input generated by {@see $unselect}.
     * When {@see $checkboxOptions} is a `Closure`, `form` and `disabled` attributes cannot be inherited
     * automatically. Use this property to set them explicitly in that case.
     */
    public $unselectOptions = [];
    /**
     * @var array|\Closure the HTML attributes for checkboxes. This can either be an array of
     * attributes or an anonymous function ([[Closure]]) that returns such an array.
     * The signature of the function should be the following: `function ($model, $key, $index, $column)`.
     * Where `$model`, `$key`, and `$index` refer to the model, key and index of the row currently being rendered
     * and `$column` is a reference to the [[CheckboxColumn]] object.
     * A function may be used to assign different attributes to different rows based on the data in that row.
     * Specifically if you want to set a different value for the checkbox
     * you can use this option in the following way (in this example using the `name` attribute of the model):
     *
     * ```
     * 'checkboxOptions' => function ($model, $key, $index, $column) {
     *     return ['value' => $model->name];
     * }
     * ```
     *
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $checkboxOptions = [];
    /**
     * @var bool whether it is possible to select multiple rows. Defaults to `true`.
     */
    public $multiple = true;
    /**
     * @var string the css class that will be used to find the checkboxes.
     * @since 2.0.9
     */
    public $cssClass;
    /**
     * @var array|ClientScriptInterface|null the client-side script implementation.
     * When [[Application::$useJquery]] is `true`, defaults to [[CheckboxColumnJqueryClientScript]].
     * Set to `null` to disable client-side script registration for this column.
     */
    public $clientScript = null;

    /**
     * @var bool whether unselect hidden input is already rendered.
     */
    private bool $_unselectRendered = false;

    /**
     * {@inheritdoc}
     * @throws \yii\base\InvalidConfigException if [[name]] is not set.
     */
    public function init()
    {
        parent::init();

        if (empty($this->name)) {
            throw new InvalidConfigException('The "name" property must be set.');
        }

        if (substr_compare($this->name, '[]', -2, 2)) {
            $this->name .= '[]';
        }

        if ($this->clientScript === null && (Yii::$app->useJquery ?? false)) {
            $this->clientScript = ['class' => CheckboxColumnJqueryClientScript::class];
        }

        if ($this->clientScript !== null && !$this->clientScript instanceof ClientScriptInterface) {
            $this->clientScript = Yii::createObject($this->clientScript);
        }

        $this->registerClientScript();
    }

    /**
     * Renders the header cell content.
     * The default implementation simply renders [[header]].
     * This method may be overridden to customize the rendering of the header cell.
     *
     * @return string The rendering result.
     */
    protected function renderHeaderCellContent()
    {
        $hiddenInput = $this->renderUnselectHiddenInput();

        if ($this->header !== null || !$this->multiple) {
            return $hiddenInput . parent::renderHeaderCellContent();
        }

        return $hiddenInput . Html::checkbox(
            $this->getHeaderCheckBoxName(),
            false,
            ['class' => 'select-on-check-all'],
        );
    }

    /**
     * {@inheritdoc}
     */
    protected function renderDataCellContent($model, $key, $index)
    {
        $hiddenInput = !$this->grid->showHeader ? $this->renderUnselectHiddenInput() : '';

        if ($this->content !== null) {
            return $hiddenInput . parent::renderDataCellContent($model, $key, $index);
        }

        if ($this->checkboxOptions instanceof Closure) {
            $options = call_user_func($this->checkboxOptions, $model, $key, $index, $this);
        } else {
            $options = $this->checkboxOptions;
        }

        if (!isset($options['value'])) {
            $options['value'] = is_array($key) ? Json::encode($key) : $key;
        }

        if ($this->cssClass !== null) {
            Html::addCssClass($options, $this->cssClass);
        }

        return $hiddenInput . Html::checkbox($this->name, !empty($options['checked']), $options);
    }

    /**
     * Returns header checkbox name.
     * @return string header checkbox name
     * @since 2.0.8
     */
    protected function getHeaderCheckBoxName()
    {
        $name = Html::getInputNameWithoutBrackets($this->name);
        if (substr_compare($name, ']', -1, 1) === 0) {
            $name = substr($name, 0, -1) . '_all]';
        } else {
            $name .= '_all';
        }

        return $name;
    }

    /**
     * Renders hidden input used for unselect value.
     */
    protected function renderUnselectHiddenInput(array $checkboxOptions = []): string
    {
        if ($this->_unselectRendered || $this->unselect === null) {
            return '';
        }

        $this->_unselectRendered = true;

        return Html::hiddenInput(
            Html::getInputNameWithoutBrackets($this->name),
            $this->unselect,
            $this->getUnselectHiddenInputOptions($checkboxOptions),
        );
    }

    /**
     * Returns hidden input attributes for unselect value.
     *
     * Attributes are resolved in this order:
     * - if {@see $unselectOptions} is set, it takes precedence.
     * - otherwise, `form` and `disabled` are inherited from `$checkboxOptions` (resolved per-row) or from the static
     *   {@see $checkboxOptions} array. When {@see $checkboxOptions} is a `Closure` and the hidden input is rendered in
     *   the header (no row context), inheritance is skipped — use {@see $unselectOptions} instead.
     */
    protected function getUnselectHiddenInputOptions(array $checkboxOptions = []): array
    {
        if ($this->unselectOptions !== []) {
            return $this->unselectOptions;
        }

        if ($checkboxOptions === [] && is_array($this->checkboxOptions)) {
            $checkboxOptions = $this->checkboxOptions;
        }

        $hiddenOptions = [];

        if (isset($checkboxOptions['form'])) {
            $hiddenOptions['form'] = $checkboxOptions['form'];
        }

        if (!empty($checkboxOptions['disabled'])) {
            $hiddenOptions['disabled'] = $checkboxOptions['disabled'];
        }

        return $hiddenOptions;
    }

    /**
     * Registers the needed JavaScript.
     * @since 2.0.8
     */
    public function registerClientScript()
    {
        if ($this->clientScript instanceof ClientScriptInterface) {
            $this->clientScript->register(
                $this,
                $this->grid->getView(),
                ['headerCheckBoxName' => $this->getHeaderCheckBoxName()],
            );
        }
    }
}
